---
name: Charts (Reusable)

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to checkout'
        required: false
        type: string
        default: ${{ github.ref }}

permissions:
  contents: read

jobs:
  charts:
    runs-on: ubuntu-latest
    name: Charts
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Install Deps
        uses: ./.github/actions/setup-deps

      - name: Build Charts
        shell: bash
        run: |
          make charts

      - name: Collect Job Logs
        uses: ./.github/actions/collect-logs
        if: always()

      - name: Collect Chart Artifacts
        shell: bash
        run: |
          mkdir /tmp/charts
          cp ./charts/*.tgz /tmp/charts
          tar cf /tmp/charts.tar -C /tmp charts

      - name: Upload Chart Tarball
        uses: actions/upload-artifact@v4
        with:
          name: charts.tar
          path: /tmp/charts.tar
          retention-days: 7
          if-no-files-found: error
