name: Dev Container

on:
  push:
    branches: [ main ]
    tags: [ 'dev-*' ]
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yaml'
  pull_request:
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yaml'
  workflow_dispatch:

jobs:
  build-devcontainer:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: ${{ startsWith(github.ref, 'refs/tags/dev-') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/emissary-ingress/emissary-dev
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-

      - name: Extract Go version from go.mod
        id: go-version
        run: echo "version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .devcontainer
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/dev-') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GO_MOD_VERSION=${{ steps.go-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
