name: repatriate-to-lts
on:
  push:
    branches:
      - release/v2.0

jobs:
  repatriate-to-master:
    runs-on: ubuntu-latest
    name: repatriate-to-master
    env:
      REF: ${{ github.ref }}
      RUN: ${{ github.run_id }}
      PUSH_ID: ${{ github.event.push_id }}
      GITHUB_TOKEN: ${{ secrets.GH_GITHUB_API_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Repatriate branch PR
        shell: bash
        run: |
          set -x
          echo "${GITHUB_TOKEN}" > temp_credential
          # GH does NOT want this in the env
          export GITHUB_TOKEN=
          cat temp_credential | gh auth login --with-token
          rm temp_credential
          gh pr create --title "[CI] repatriate changes to master job ${RUN}" \
                       --body "This PR contains changes from push to release/v2.0 ${REF}" \
                       --base master \
                       --reviewer "kflynn,aidanhahn,lukeshu,anodelman"
      - name: Slack notification
        if: always()
        uses: edge/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          success_text: "Created repatriation PR for push to release/v2.0"
          failure_text: "Couldn\'t cleanly repatriate changes back to master"
          fields: |
            [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
             { "title": "Branch", "value": "${env.GITHUB_REF}", "short": true}]
